### PR TITLE
Run cloudsqlproxy service as root

### LINKED ISSUE #1761: cloudsqlproxy service failed to start
Due to insufficient permissions

Error message:

> google: error getting credentials using well-known file (/home/ubuntu/.config/gcloud/application_default_credentials.json): open /home/ubuntu/.config/gcloud/application_default_credentials.json: permission denied

### PR DESCRIPTION
**Pull request by joecheuk**
Removed User= from cloudsqlproxy service.

By default, Systemd starts the executable stated in ExecStart= as root so it will contain the permissions required to run the cloudsqlproxy script.

Resolves #1761

### CODE REVIEW

File: install/gcp/scripts/initialize_forseti_services.sh [hunk 1]
```diff
@@ -66,7 +66,6 @@ SQL_PROXY_SERVICE="$(cat << EOF
 [Unit]
 Description=Cloud SQL Proxy
 [Service]
-User=ubuntu
```
Comment (blueandgold) [inline install/gcp/scripts/initialize_forseti_services.sh]: Can you please just add a comment here:
```
# See issue #1761 for why this needs to be run as root.
```

Comment (joecheuk) [reply install/gcp/scripts/initialize_forseti_services.sh]: Updated.
